import type { VehicleRow } from "~/types/vehicle"

export const vehiclesMock: VehicleRow[] = [
  {
    id: "1",
    year: 2021,
    make: "Toyota",
    model: "Camry",
    trim: "SE",
    bodyType: "sedan",
    fuelType: "gasoline",
    drivetrain: "fwd",
    odometer: 34500,
    price: 25990,
    status: "available",
  },
  {
    id: "2",
    year: 2022,
    make: "Honda",
    model: "CR-V",
    trim: "EX",
    bodyType: "suv",
    fuelType: "hybrid",
    drivetrain: "awd",
    odometer: 12000,
    price: 34990,
    status: "available",
  },
  {
    id: "3",
    year: 2019,
    make: "Ford",
    model: "F-150",
    trim: "XLT",
    bodyType: "truck",
    fuelType: "gasoline",
    drivetrain: "4wd",
    odometer: 78500,
    price: 28950,
    status: "sold",
  },
  {
    id: "4",
    year: 2020,
    make: "Tesla",
    model: "Model 3",
    trim: "Long Range",
    bodyType: "sedan",
    fuelType: "electric",
    drivetrain: "awd",
    odometer: 22000,
    price: 44990,
    status: "available",
  },
  {
    id: "5",
    year: 2023,
    make: "BMW",
    model: "X5",
    trim: "xDrive40i",
    bodyType: "suv",
    fuelType: "gasoline",
    drivetrain: "awd",
    odometer: 5200,
    price: 67990,
    status: "available",
  },
  {
    id: "6",
    year: 2018,
    make: "Audi",
    model: "A4",
    trim: "Progressiv",
    bodyType: "sedan",
    fuelType: "gasoline",
    drivetrain: "awd",
    odometer: 45600,
    price: 22500,
    status: "available",
  },
  {
    id: "7",
    year: 2021,
    make: "Chevrolet",
    model: "Silverado 1500",
    trim: "LT",
    bodyType: "truck",
    fuelType: "gasoline",
    drivetrain: "4wd",
    odometer: 28700,
    price: 32950,
    status: "pending",
  },
  {
    id: "8",
    year: 2022,
    make: "Mazda",
    model: "CX-5",
    trim: "GS",
    bodyType: "suv",
    fuelType: "gasoline",
    drivetrain: "awd",
    odometer: 18900,
    price: 29990,
    status: "available",
  },
  {
    id: "9",
    year: 2020,
    make: "Nissan",
    model: "Altima",
    trim: "SV",
    bodyType: "sedan",
    fuelType: "gasoline",
    drivetrain: "fwd",
    odometer: 31200,
    price: 21990,
    status: "available",
  },
  {
    id: "10",
    year: 2023,
    make: "Hyundai",
    model: "Tucson",
    trim: "Preferred",
    bodyType: "suv",
    fuelType: "hybrid",
    drivetrain: "awd",
    odometer: 8500,
    price: 35990,
    status: "available",
  },
  {
    id: "11",
    year: 2019,
    make: "Jeep",
    model: "Wrangler",
    trim: "Sport",
    bodyType: "suv",
    fuelType: "gasoline",
    drivetrain: "4wd",
    odometer: 42300,
    price: 31990,
    status: "available",
  },
  {
    id: "12",
    year: 2021,
    make: "Volkswagen",
    model: "Jetta",
    trim: "Highline",
    bodyType: "sedan",
    fuelType: "gasoline",
    drivetrain: "fwd",
    odometer: 25400,
    price: 24990,
    status: "reserved",
  },
  {
    id: "13",
    year: 2020,
    make: "Subaru",
    model: "Outback",
    trim: "Touring",
    bodyType: "wagon",
    fuelType: "gasoline",
    drivetrain: "awd",
    odometer: 36800,
    price: 28990,
    status: "available",
  },
  {
    id: "14",
    year: 2022,
    make: "Kia",
    model: "Sorento",
    trim: "LX",
    bodyType: "suv",
    fuelType: "gasoline",
    drivetrain: "awd",
    odometer: 15600,
    price: 33990,
    status: "available",
  },
  {
    id: "15",
    year: 2023,
    make: "Mercedes-Benz",
    model: "C-Class",
    trim: "C 300",
    bodyType: "sedan",
    fuelType: "gasoline",
    drivetrain: "awd",
    odometer: 3200,
    price: 54990,
    status: "available",
  },
]
